Feature/holo 523 add health check port
holographxyz/holograph-cli pull request #198
Opened 2022-10-21 14:46 UTC by BravoNatalie

## Describe Changes

- Created `src/base-commands/baseCommands` to hold global flags 
- Created custom hook `src/hooks/healthCheck.ts` to launch healthCheck server.
- Altered `src/commands/operator/index.ts/` to handle new implementation of healthCheck.

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] Code styles have been enforced
- [x] I have checked eslint

2022-10-21 16:55 UTC, sogoiii requested changes
## Healthcheck not returning connected status
When I run operator on Terminal A and then run a curl command on Terminal B, i get the following.

```
➜ curl localhost:6001/healthcheck
{"status":"alive","providerStatus":{}}%   
```
The key "providerStatus" should have more data around which networks were connected.

## Change not applied to indexer

I only see this being used on operator. Did you do that to test that it works before applying to indexer? Just FYI, you dont have to update propagator.

2022-10-24 15:11 UTC, sogoiii requested changes

2022-10-24 18:24 UTC, alexanderattar submitted a review, later dismissed

2022-11-09 00:02 UTC, sogoiii commented
@BravoNatalie I get this error when i run your branch:

```
➜ env HOLOGRAPH_ENVIRONMENT=experimental ./bin/dev operator --networks fuji --healthCheck
(node:59398) TSError Plugin: @holographxyz/cli: ⨯ Unable to compile TypeScript:
src/commands/operator/index.ts:54:17 - error TS2513: Abstract method 'run' in class 'Command' cannot be accessed via super expression.

54     await super.run()
                   ~~~

module: @oclif/core@1.16.4
task: toCached
plugin: @holographxyz/cli
root: /Users/apozo/Documents/company/cxip/codebase/holo-cli
See more details with DEBUG=*
(Use `node --trace-warnings ...` to show where the warning was created)
(node:59398) TSError Plugin: @holographxyz/cli: ⨯ Unable to compile TypeScript:
src/commands/operator/index.ts:54:17 - error TS2513: Abstract method 'run' in class 'Command' cannot be accessed via super expression.

54     await super.run()
                   ~~~

module: @oclif/core@1.16.4

```

2022-11-09 19:11 UTC, sogoiii approved these changes
👍

2022-11-09 19:44 UTC, merged