Improvement / HOLO 772 indexer processor handle mint integration
holographxyz/holograph-cli pull request #392
Opened 2023-01-26 18:25 UTC by BravoNatalie

## Describe Changes

- Change A
- Change B

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] Code styles have been enforced
- [ ] I have checked eslint

2023-01-26 19:06 UTC, sogoiii requested changes

2023-01-26 19:06 UTC, sogoiii commented on src/handlers/indexer/handle-mint-event.ts
> +  const receipt: TransactionReceipt | null = await networkMonitor.getTransactionReceipt({
@BravoNatalie @alexanderattar 

So i think we can push more work to job consumer. The CLI only has to detect the new event and send a job. That way we simplify the CLI to be a block / event parser.

2023-01-26 19:06 UTC, sogoiii commented on src/commands/indexer/index.ts
> +              await handleMintEvent.call(this, this.networkMonitor, transaction, job.network, tags)
@BravoNatalie @alexanderattar I also think we should have the original handler and the new handler that submits a job. That way we can transition from on version to anther. Aka `handlers/handle-mint-events.ts` is the original and the new `handler/handle-mint-eventsv2.ts` that only submits a job. Or we just make a new generic job sender function that is called here. In short, what would be a good method to follow to transition into the new setup.

2023-01-26 21:43 UTC, BravoNatalie commented on src/commands/indexer/index.ts
> +              await handleMintEvent.call(this, this.networkMonitor, transaction, job.network, tags)
I agree, we can have both implementations for the transition.

2023-02-03 19:49 UTC, sogoiii approved these changes
👍

2023-02-03 19:49 UTC, merged