Feature/update cli to match latest drop contracts
holographxyz/holograph-cli pull request #429
Opened 2023-03-20 18:41 UTC by alexanderattar

## Describe Changes

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] Code styles have been enforced
- [ ] I have checked eslint

2023-03-20 18:42 UTC, alexanderattar commented on src/commands/create/contract.ts
> +      gasPrice: ethers.BigNumber.from(100_000_000_000), // 100 gwei
temporarily overriding here to force the tx to go through

2023-03-21 19:44 UTC, sogoiii requested changes
I think if we should convert some of those hardcoded string references in to variables.

2023-03-21 19:44 UTC, sogoiii commented on src/commands/create/contract.ts
> +            contractType = 'HolographDropERC721'
would be it worth it to put `contractType = BytecodeType.HolographDropERC721` instead?

2023-03-21 19:44 UTC, sogoiii commented on src/commands/create/contract.ts
> +    const contractTypes: string[] = ['HolographERC20', 'HolographERC721', 'HolographDropERC721']
should we reference the values in `BytecodeType.HolographDropERC721` and such?

2023-03-21 19:44 UTC, sogoiii commented on src/commands/create/contract.ts
> +          case 'HolographDropERC721': {
should we set this as `BytecodeType.HolographDropERC72`? and other cases as well.

2023-03-21 19:44 UTC, sogoiii commented on src/commands/create/contract.ts
> +            const rendererFactory = new ContractFactory(renderAbi, EditionsMetadataRenderer.bytecode, account)
So we have the method getABIs that is a large map of contracts. Shold we add that there? This hardcodes develop as well. Which i guess ok for now ,but we should make sure to update this before promoting to testnet.

2023-03-21 19:44 UTC, sogoiii commented on src/commands/create/nft.ts
> +        abiPath = path.join(__dirname, `../../abi/${environment}/HolographDropERC721.json`)
Should we grab this from the `getABIs` function?

2023-03-24 18:03 UTC, sogoiii approved these changes
👍

2023-03-24 18:03 UTC, merged